### ISSUE TITLE
how to call a extension

### ISSUE THREAD

**Issue by guairedlein** [OrchardForexTutorials/framework_3#4]
Include/Orchard/Frameworks/Framework_3.06/Extensions/TimeFilter.mqh

is an error that filter is not in \Frameworks\Framework_3.06\Framework.mqh

or i need to include in the expert.mqh?

**Comment by OrchardForexTutorials** [comment]
The filters are not intended to be loaded by framework.mqh, mainly because they may not be needed and to keep the code smaller.
Load the filters directly from your expert.
I generally include a config.mqh file in my expert with all includes, then include the config.mqh in the expert.

**Comment by guairedlein** [comment]
thx!
